export const FIGHTER_LOAD_REQUEST = "FIGHTER_REQUEST";
export const FIGHTER_LOAD_SUCCESS = "FIGHTER_LOAD_SUCCESS";
export const FIGHTER_LOAD_FAILURE = "FIGHTER_LOAD_FAILURE";
export const SEGMENT_UPDATE_PARAM = "SEGMENT_UPDATE_PARAM";
export const DESCRIPTION_UPDATE_TEXT = "DESCRIPTION_UPDATE_TEXT"