export default [
{id: '1', fighter_name: "Mario", url: "mario", title: "Mr. Video Game Himself", image: "/fighters_img/mario.png", icon: "/fighters_icon/mario.png"},
{id: '2', fighter_name: "Donkey Kong", url: "donkey_kong", title: "King of the Jungle", image: "/fighters_img/donkey_kong.png", icon: "/fighters_icon/donkey_kong.png"},
{id: '3', fighter_name: "Link", url: "link", title: "Champion of Hyrule", image: "/fighters_img/link.png", icon: "/fighters_icon/link.png"},
{id: '4', fighter_name: "Samus", url: "samus", title: "Bounty Hunter Extraordinaire", image: "/fighters_img/samus.png", icon: "/fighters_icon/samus.png"},
{id: '4e', fighter_name: "Dark Samus", url: "dark_samus", title: "Phazon Incarnate", image: "/fighters_img/dark_samus.png", icon: "/fighters_icon/dark_samus.png"},
{id: '5', fighter_name: "Yoshi", url: "yoshi", title: "Omnivore of the Year", image: "/fighters_img/yoshi.png", icon: "/fighters_icon/yoshi.png"},
{id: '6', fighter_name: "Kirby", url: "kirby", title: "The Pink Demon", image: "/fighters_img/kirby.png", icon: "/fighters_icon/kirby.png"},
{id: '7', fighter_name: "Fox", url: "fox", title: "Leader of Star Fox", image: "/fighters_img/fox.png", icon: "/fighters_icon/fox.png"},
{id: '8', fighter_name: "Pikachu", url: "pikachu", title: "Pika Pika!", image: "/fighters_img/pikachu.png", icon: "/fighters_icon/pikachu.png"},
{id: '9', fighter_name: "Luigi", url: "luigi", title: "The Eternal Understudy", image: "/fighters_img/luigi.png", icon: "/fighters_icon/luigi.png"},
{id: '10', fighter_name: "Ness", url: "ness", title: "The PSI Powerhouse", image: "/fighters_img/ness.png", icon: "/fighters_icon/ness.png"},
{id: '11', fighter_name: "Captain Falcon", title: "The Supersonic Slugger", url: "captain_falcon", image: "/fighters_img/captain_falcon.png", icon: "/fighters_icon/captain_falcon.png"},
{id: '12', fighter_name: "Jigglypuff", title: "The Sleepy Singer", url: "jigglypuff", image: "/fighters_img/jigglypuff.png", icon: "/fighters_icon/jigglypuff.png"},
{id: '13', fighter_name: "Peach", url: "peach", title: "Princess of Toadstools", image: "/fighters_img/peach.png", icon: "/fighters_icon/peach.png"},
{id: '13e', fighter_name: "Daisy", url: "daisy", title: "Sarasaland's Chipper Princess", image: "/fighters_img/daisy.png", icon: "/fighters_icon/daisy.png"},
{id: '14', fighter_name: "Bowser", url: "bowser", title: "King of the Koopas", image: "/fighters_img/bowser.png", icon: "/fighters_icon/bowser.png"},
{id: '15', fighter_name: "Ice Climbers", url: "ice_climbers", title: "Bone-Chilling Duo", image: "/fighters_img/ice_climbers.png", icon: "/fighters_icon/ice_climbers.png"},
{id: '16', fighter_name: "Sheik", url: "sheik", title: "The Illusive Sheikah", image: "/fighters_img/sheik.png", icon: "/fighters_icon/sheik.png"},
{id: '17', fighter_name: "Zelda", url: "zelda", title: "Hyrule's Wise Princess", image: "/fighters_img/zelda.png", icon: "/fighters_icon/zelda.png"},
{id: '18', fighter_name: "Dr. Mario", url: "dr_mario", title: "The Prescriber", image: "/fighters_img/dr_mario.png", icon: "/fighters_icon/dr_mario.png"},
{id: '19', fighter_name: "Pichu", url: "pichu", title: "Shockingly Adorable", image: "/fighters_img/pichu.png", icon: "/fighters_icon/pichu.png"},
{id: '20', fighter_name: "Falco", url: "falco", title: "Proud Space Ace", image: "/fighters_img/falco.png", icon: "/fighters_icon/falco.png"},
{id: '21', fighter_name: "Marth", url: "marth", title: "The Hero-King", image: "/fighters_img/marth.png", icon: "/fighters_icon/marth.png"},
{id: '21e', fighter_name: "Lucina", url: "lucina", title: "Warrior from a Doomed Future", image: "/fighters_img/lucina.png", icon: "/fighters_icon/lucina.png"},
{id: '22', fighter_name: "Young Link", url: "young_link", title: "Master of Ocarina", image: "/fighters_img/young_link.png", icon: "/fighters_icon/young_link.png"},
{id: '23', fighter_name: "Ganondorf", url: "ganondorf", title: "The King of Darkness", image: "/fighters_img/ganondorf.png", icon: "/fighters_icon/ganondorf.png"},
{id: '24', fighter_name: "Mewtwo", url: "mewtwo", title: "A Legend Reawakens", image: "/fighters_img/mewtwo.png", icon: "/fighters_icon/mewtwo.png"},
{id: '25', fighter_name: "Roy", url: "roy", title: "The Young Lion", image: "/fighters_img/roy.png", icon: "/fighters_icon/roy.png"},
{id: '25e', fighter_name: "Chrom", url: "chrom", title: "Prince of Ylisse", image: "/fighters_img/chrom.png", icon: "/fighters_icon/chrom.png"},
{id: '26', fighter_name: "Mr. Game & Watch", url: "mr_game_and_watch", title: "Master of Two Dimensions", image: "/fighters_img/mr_game_and_watch.png", icon: "/fighters_icon/mr_game_and_watch.png"},
{id: '27', fighter_name: "Meta Knight", url: "meta_knight", title: "The Masked Swordsman", image: "/fighters_img/meta_knight.png", icon: "/fighters_icon/meta_knight.png"},
{id: '28', fighter_name: "Pit", url: "pit", image: "/fighters_img/pit.png", title: "Captain of Lady Palutena's Guard", icon: "/fighters_icon/pit.png"},
{id: '28e', fighter_name: "Dark Pit", url: "dark_pit", title: "Dark-Winged Doppelgänger", image: "/fighters_img/dark_pit.png", icon: "/fighters_icon/dark_pit.png"},
{id: '29', fighter_name: "Zero Suit Samus", url: "zero_suit_samus", title: "The Warrior Within", image: "/fighters_img/zero_suit_samus.png", icon: "/fighters_icon/zero_suit_samus.png"},
{id: '30', fighter_name: "Wario", url: "wario", title: "Scoundrel with a Fart of Gold", image: "/fighters_img/wario.png", icon: "/fighters_icon/wario.png"},
{id: '31', fighter_name: "Snake", url: "snake", title: "The Legendary Mercenary", image: "/fighters_img/snake.png", icon: "/fighters_icon/snake.png"},
{id: '32', fighter_name: "Ike", url: "ike", title: "The Radiant Hero of Legend", image: "/fighters_img/ike.png", icon: "/fighters_icon/ike.png"},
{id: '33-35', fighter_name: "Pokemon Trainer", url: "pokemon_trainer", title: "Wants to Be the Very Best", image: "/fighters_img/pokemon_trainer.png", icon: "/fighters_icon/pokemon_trainer.png"},
{id: '36', fighter_name: "Diddy Kong", url: "diddy_kong", title: "The Acrobat", image: "/fighters_img/diddy_kong.png", icon: "/fighters_icon/diddy_kong.png"},
{id: '37', fighter_name: "Lucas", url: "lucas", title: "Boy from Nowhere", image: "/fighters_img/lucas.png", icon: "/fighters_icon/lucas.png"},
{id: '38', fighter_name: "Sonic", url: "sonic", title: "The Blue Blur", image: "/fighters_img/sonic.png", icon: "/fighters_icon/sonic.png"},
{id: '39', fighter_name: "King Dedede", url: "king_dedede", title: "Self-Made King", image: "/fighters_img/king_dedede.png", icon: "/fighters_icon/king_dedede.png"},
{id: '40', fighter_name: "Olimar", url: "olimar", title: "Veteran Astronaut", image: "/fighters_img/olimar.png", icon: "/fighters_icon/olimar.png"},
{id: '41', fighter_name: "Lucario", url: "lucario", title: "Master of Aura", image: "/fighters_img/lucario.png", icon: "/fighters_icon/lucario.png"},
{id: '42', fighter_name: "R.O.B.", url: "rob", title: "The Last of His Kind", image: "/fighters_img/rob.png", icon: "/fighters_icon/rob.png"},
{id: '43', fighter_name: "Toon Link", url: "toon_link", title: "Wind-Walking Warrior", image: "/fighters_img/toon_link.png", icon: "/fighters_icon/toon_link.png"},
{id: '44', fighter_name: "Wolf", url: "wolf", title: "The Silver Space Wolf", image: "/fighters_img/wolf.png", icon: "/fighters_icon/wolf.png"},
{id: '45', fighter_name: "Villager", url: "villager", title: "Mayor of Smallville", image: "/fighters_img/villager.png", icon: "/fighters_icon/villager.png"},
{id: '46', fighter_name: "Mega Man", url: "mega_man", title: "The Blue Bomber", image: "/fighters_img/mega_man.png", icon: "/fighters_icon/mega_man.png"},
{id: '47', fighter_name: "Wii Fit Trainer", url: "wii_fit_trainer", title: "Yoga Warrior", image: "/fighters_img/wii_fit_trainer.png", icon: "/fighters_icon/wii_fit_trainer.png"},
{id: '48', fighter_name: "Rosalina & Luma", url: "rosalina_and_luma", title: "The Cosmic Travellers", image: "/fighters_img/rosalina_and_luma.png", icon: "/fighters_icon/rosalina_and_luma.png"},
{id: '49', fighter_name: "Little Mac", url: "litte_mac", title: "Bruiser from the Bronx", image: "/fighters_img/little_mac.png", icon: "/fighters_icon/little_mac.png"},
{id: '50', fighter_name: "Greninja", url: "greninja", title: "Master of Stealth", image: "/fighters_img/greninja.png", icon: "/fighters_icon/greninja.png"},
{id: '51', fighter_name: "Mii Brawler", url: "mii_brawler", title: "The Brawler of Many Faces", image: "/fighters_img/mii_fighter.png", icon: "/fighters_icon/mii_fighter.png"},
{id: '52', fighter_name: "Mii Swordfighter", url: "mii_swordfighter", title: "The Swordfighter of Many Faces", image: "/fighters_img/mii_fighter.png", icon: "/fighters_icon/mii_fighter.png"},
{id: '53', fighter_name: "Mii Gunner", url: "mii_gunner", title: "The Gunner of Many Faces", image: "/fighters_img/mii_fighter.png", icon: "/fighters_icon/mii_fighter.png"},
{id: '54', fighter_name: "Palutena", url: "palutena", title: "Goddess of Light", image: "/fighters_img/palutena.png", icon: "/fighters_icon/palutena.png"},
{id: '55', fighter_name: "PAC-MAN", url: "pacman", title: "The Yellow Bane of Ghosts", image: "/fighters_img/pac_man.png", icon: "/fighters_icon/pac_man.png"},
{id: '56', fighter_name: "Robin", url: "robin", title: "The Tactician Magician", image: "/fighters_img/robin.png", icon: "/fighters_icon/robin.png"},
{id: '57', fighter_name: "Shulk", url: "shulk", title: "The Visionary", image: "/fighters_img/shulk.png", icon: "/fighters_icon/shulk.png"},
{id: '58', fighter_name: "Bowser Jr.", url: "bowser_jr", title: "Prince of the Koopas", image: "/fighters_img/bowser_jr.png", icon: "/fighters_icon/bowser_jr.png"},
{id: '59', fighter_name: "Duck Hunt", url: "duck_hunt", title: "Bark, Quack, Boom!", image: "/fighters_img/duck_hunt.png", icon: "/fighters_icon/duck_hunt.png"},
{id: '60', fighter_name: "Ryu", url: "ryu", title: "Eternal Wanderer", image: "/fighters_img/ryu.png", icon: "/fighters_icon/ryu.png"},
{id: '60e', fighter_name: "Ken", url: "ken", title: "The Fire-Breathing Fist", image: "/fighters_img/ken.png", icon: "/fighters_icon/ken.png"},
{id: '61', fighter_name: "Cloud", url: "cloud", title: "SOLDIER 1st Class", image: "/fighters_img/cloud.png", icon: "/fighters_icon/cloud.png"},
{id: '62', fighter_name: "Corrin", url: "corrin", title: "Blood of Dragons", image: "/fighters_img/corrin.png", icon: "/fighters_icon/corrin.png"},
{id: '63', fighter_name: "Bayonetta", url: "bayonetta", title: "Umbra Witch", image: "/fighters_img/bayonetta.png", icon: "/fighters_icon/bayonetta.png"},
{id: '64', fighter_name: "Inkling", url: "inkling", title: "Part Kid, Part Squid", image: "/fighters_img/inkling.png", icon: "/fighters_icon/inkling.png"},
{id: '65', fighter_name: "Ridley", url: "ridley", title: "Cunning God of Death", image: "/fighters_img/ridley.png", icon: "/fighters_icon/ridley.png"},
{id: '66', fighter_name: "Simon", url: "simon", title: "Evil's Whip-Wielding Bane", image: "/fighters_img/simon.png", icon: "/fighters_icon/simon.png"},
{id: '66e', fighter_name: "Richter", url: "richter", title: "Azure Vampire Assassin", image: "/fighters_img/richter.png", icon: "/fighters_icon/richter.png"},
{id: '67', fighter_name: "King K. Rool", url: "king_k_rool", title: "The Kremling Commander", image: "/fighters_img/king_k_rool.png", icon: "/fighters_icon/king_k_rool.png"},
{id: '68', fighter_name: "Isabelle", url: "isabelle", title: "The Mayor's Assistant", image: "/fighters_img/shizue.png", icon: "/fighters_icon/isabelle.png"},
{id: '69', fighter_name: "Incineroar", url: "incineroar", title: "The Ring's Raging Flame", image: "/fighters_img/gaogaen.png", icon: "/fighters_icon/incineroar.png"},
{id: '70', fighter_name: "Piranha Plant", url: "piranha_plant", title: "Bloom of Your Doom", image: "/fighters_img/packun_flower.png", icon: "/fighters_icon/piranha_plant.png"},
{id: '71', fighter_name: "Joker", url: "joker", title: "", image: "/fighters_img/joker.png", icon: ""},
]